version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres_con
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    image: node
    container_name: node_on_postgres_con
    restart: unless-stopped
    ports:
      - 3000:${Port}
    depends_on:
      - db
    env_file:
      - .env


volumes:
  db_data: