version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres_con
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    image: node
    container_name: node_on_postgres_con
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env


volumes:
  db_data: